### ISSUE TITLE
The official TODO list

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Linux-autohost#1]
### New features
- [x] Help command (-h|--help)
- [x] Quiet command (-q|--quiet)
- [x] Database creation (-D|--database)
- [x] Supprimer une configuration précédente (-r|--remove)
- [x] DocumentRoot argument (-d|--docroot)

### Enhancement
- [x] Agruments verification
- [x] Check if files and/or folder does not already exists with the same name before the script create them
- [x] Check if Apache and MySQL are properly installed before going on (use  `dpkg -s module_name`)
- [x] Remove command should clean hosts file
- [ ] Remove command should be able to delete a database
- [x] ~~Check if Apache and MySQL services are running before the script~~ Not needed since we now use the `start` command
- [ ] Add a flag `list` which gives the list of all local websites created

### Others
- [x] Redact the readme
- [x] Regularly create releases .deb, .tar.gz, .zip
- [ ] Create `install` and `uninstall` commands
